### ISSUE TITLE
Написать описание продукта (в том числе на английском)

### ISSUE THREAD

**Issue by lpvmak** [lpvmak/med_sched#32]

**Comment by mashaverdina** [comment]
> A service that allows you to create medication plans and add them to your calendar.

Здесь не может быть "A", это же вот этот вполне себе определенный сервис. Наверное, просто без артикля? 

То, что написано в функциональности лучше перенести в описание продукта сверху. 

> Устанавливать сроки приема препората

Опечатка в слове "препАрата".

Вообще я на первый взгляд видела у вас с ридми сразу 3-4 опечатки. Это много. Постарайтесь читать внимательнее, может быть поможет, если кто-то второй из команды будет перечитывать.

**Comment by mashaverdina** [comment]
* То, что написано в функциональности лучше перенести в описание продукта сверху, ну и перевести на английский
