### ISSUE TITLE
Сформулировать стандарт кодирования

### ISSUE THREAD

**Issue by lpvmak** [lpvmak/med_sched#33]

**Comment by mashaverdina** [comment]
> В разработке мы используем язык JavaScript + JSX (React) и придерживаемся Google JavaScript Style стиля кодирования.

Можно убрать в конце "стиля кодирования".

Предлагаю раздел для команды разработки тоже вынести в отдельный файл, например в Development.md или в тот же Contributing.md. В первом случае требования к коммитам тоже продублировать в contributing.

В требованиях к коммиту не указано, что нужно цеплять коммит к тикету. там вроде #{номер_тикета}.

Может стоит добавить какое-то легкое требование именованию веток? Когда вообще создаются ветки? feature на каждую issue? как-то иначе?

**Comment by KoDim97** [comment]
Завтра исправлю замечания.
Для разработчиков вынесу в отдельный файл. 

Про требования к коммитам если совсем честно не понял сначала, что так можно, но Женя уже показала мне и оформила коммит правильно, сделаю тоже.

С ветками вообще сложно. А точнее -- сложно понять как применить все это к нашему проекту. У нас будет проблематично найти задач на параллельную разработку всем, плюс изначально не планировалось, что непосредственно с реактом будет работать каждый, так например Женя пока написала генератор отдельными .js файлами. И вот куда это класть? Пока решили в мастер в отдельную папку. А надо было создать новую ветвь features с номером тикета и туда? Оно же не будет непосредственно в таком виде сливаться с мастером (где будет сам проект).
В общем, с ветками я пока запутался, организуем митинг и решим этот вопрос.

**Comment by mashaverdina** [comment]
Ветки не про то, куда класть. Про то, куда класть - структура папок. Она такая, какую ты бы сделал для проекта у себя на компьютере. Вообще гит про то, что несколько человек могут работать с одним файлом одновременно, даже с одним куском кода. Затем все автоматически (иногда какие-то куски вручную) сливается в один файл в репозитории. С этой точки зрения ветки могут быть удобны тем, что позволяют пушить изменения в условно некоторую копию/версию репозитория до тех пор, пока не будет сделан какой-то кусок функциональности. Тогда не нужно будет мержить друг с другом каждый пуш, можно будет сделать это один раз. Еще можно запретить всем пушить в девелоп/мастер, и обязать всех делать пулл реквест (запрос на мерж), который можно ревьюить. Там еще много всяких вариантов. Может пересмотреть лекцию или посмотреть статью какую-нибудь. Еще вы можете по желанию упростить свои правила, сейчас у вас одна из популярных, но может она для вас окажется слишком замороченной, когда разберетесь. Если будет нужно, можем договориться о встрече на кафедре или онлайн.
